service: koop-serverless-example

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs10.x
  region: us-east-1

functions:
  getData:
    handler: src/index.handler
    events:
      - http:
          path: /my-provider/{host}/FeatureServer/0
          method: get
          cors: true
          request:
            parameters:
              paths:
                host: true
  queryData:
    handler: src/index.handler
    events:
      - http:
          path: /my-provider/{host}/FeatureServer/0/query
          method: get
          cors: true
          request:
            parameters:
              querystrings:
                where: false
              paths:
                host: true
